# Generated by Django 6.0.1 on 2026-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in your currency', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this is income or expense', max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary')], help_text='Catrgory of the transaction', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='OPtional description or notes')),
                ('date', models.DateField(help_text='Date when the transaction occured')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
