# Generated by Django 6.0.1 on 2026-01-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
