# Generated by Django 6.0.1 on 2026-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_update_at_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investments', 'Investments'), ('other_income', 'Other Income'), ('food', 'Food & Dining'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('rent', 'Rent/Mortgage'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other_expense', 'Other Expense')], help_text='Catrgory of the transaction', max_length=20),
        ),
    ]
